/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated member. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Level, XP, rank, and streak. */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-region recovery state (backs OXRecoveryMap). */
        get: operations["getRecovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The member credential (physical + digital). */
        get: operations["getCredential"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * White-label brand config for the current tenant.
         * @description Returns the brand applied by `whitelabel/apply-brand.js`. Defaults to OX when the tenant is unbranded.
         */
        get: operations["getTenantBrand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/floors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner floors near a point. */
        get: operations["listFloors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/floors/{floorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFloor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discoverable moves (backs OXExerciseCard / OXFilterBar). */
        get: operations["listExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}/floor-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Floors that have this move's equipment (backs OXFloorMatch). */
        get: operations["listFloorMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a training session from a program day. */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a set (backs OXSetRow / OXExercisePlayer). */
        post: operations["logSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish a session; returns XP earned + any level-up / PRs. */
        post: operations["finishSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tribes/{tribeId}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked tribe leaderboard (backs OXTribeBoard). */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{classId}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book a class (backs OXClassRow / OXBookingCard). */
        post: operations["bookClass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** RSVP to an event (backs OXEventCard). */
        post: operations["rsvpEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raids/{raidId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a synced raid (backs OXRaidCard / OXRaidRoom). */
        post: operations["joinRaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check in to a floor (backs OXCheckIn). */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Program↔playlist pairings for discovery (backs OXPairingCard). */
        get: operations["listPairings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairings/{pairingId}/upvote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upvote a pairing (backs OXUpvote). */
        post: operations["upvotePairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example not_found */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Page: {
            items?: unknown[];
            nextCursor?: string | null;
            total?: number;
        };
        /**
         * @description Membership tier — maps to the .ox-tier-* scope + OXTierBadge.
         * @enum {string}
         */
        Tier: "founder" | "compass" | "sound" | "distant";
        /** @description White-label brand config — consumed by whitelabel/apply-brand.js. Mirrors whitelabel/brand.schema.json. */
        BrandConfig: {
            slug: string;
            name: string;
            mark?: string;
            accent: string;
            accentDeep?: string;
            accentBright?: string;
            ground?: string;
            ink?: string;
            /** @enum {string} */
            mode?: "light" | "dark" | "auto";
            /** Format: uri-reference */
            logo?: string;
        };
        Member: {
            id: string;
            /** @example @mara */
            handle: string;
            name: string;
            initial?: string;
            tier: components["schemas"]["Tier"];
            /** @example 014 */
            memberNumber?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        Progress: {
            level: number;
            /** @example Pathfinder */
            rank?: string;
            xp: number;
            xpMax?: number;
            xpToNext: number;
            streakDays?: number;
            streakActive?: boolean;
        };
        Credential: {
            /** @enum {string} */
            material?: "physical" | "digital";
            memberNumber: string;
            fields: {
                label?: string;
                value?: string;
            }[];
            strip?: string;
            verified?: boolean;
        };
        Floor: {
            id: string;
            name: string;
            locality?: string;
            /** @example 0.4 mi */
            distance?: string;
            isHome?: boolean;
            /** @description indoor | trail | rooftop | … */
            scenery?: string;
            equipment?: components["schemas"]["Equipment"][];
        };
        Equipment: {
            id: string;
            name: string;
            count?: number;
        };
        Exercise: {
            id: string;
            index?: string;
            name: string;
            equipment?: string;
            muscles?: string;
            /** @description # of nearby floors with the gear */
            floors?: number;
        };
        FloorMatch: {
            floorId?: string;
            name?: string;
            distance?: string;
            /** @description matching equipment summary */
            has?: string;
            scenery?: string;
            xp?: number;
            isHome?: boolean;
        };
        Session: {
            id: string;
            programId?: string;
            floorId?: string;
            /** @enum {string} */
            status: "active" | "finished";
            /** Format: date-time */
            startedAt?: string;
            sets?: components["schemas"]["Set"][];
        };
        SetInput: {
            exerciseId: string;
            weight?: number;
            reps: number;
            rpe?: number;
        };
        Set: components["schemas"]["SetInput"] & {
            index?: number;
            done?: boolean;
            /** Format: date-time */
            loggedAt?: string;
        };
        SessionResult: {
            xp?: number;
            leveledUp?: boolean;
            level?: number;
            prs?: components["schemas"]["PR"][];
        };
        PR: {
            lift: string;
            value: number;
            unit?: string;
            delta?: number;
            prev?: number;
            history?: number[];
        };
        RecoveryRegion: {
            name: string;
            /** @enum {string} */
            state: "fresh" | "light" | "worked" | "spent";
        };
        LeaderboardRow: {
            rank: number;
            name: string;
            initial?: string;
            xp: number;
            me?: boolean;
        };
        Booking: {
            id: string;
            title: string;
            when: string;
            where: string;
            locality?: string;
            /** @enum {string} */
            status?: "open" | "filling" | "full" | "booked";
            code?: string;
        };
        Event: {
            id: string;
            /** @example Sat · Mar 14 */
            day: string;
            title: string;
            host?: string;
            attendees?: number;
            /** @enum {string} */
            status?: "open" | "going";
        };
        Raid: {
            id: string;
            title: string;
            when?: string;
            floor?: string;
            filled: number;
            capacity: number;
            rewardXp?: number;
            live?: boolean;
        };
        /**
         * @description Backs OXCurationBadge.
         * @enum {string}
         */
        CurationTier: "signature" | "featured" | "community";
        /**
         * @description Streaming service — backs OXServiceBadge (neutral chip, never the real logo).
         * @enum {string}
         */
        Service: "spotify" | "apple" | "soundcloud" | "tidal";
        Track: {
            id: string;
            title: string;
            artist?: string;
            /** @example 3:42 */
            dur?: string;
            bpm?: number;
            /** @description the move this song maps to */
            workout?: string;
            service?: components["schemas"]["Service"];
        };
        Pairing: {
            id: string;
            name: string;
            author?: string;
            tier?: components["schemas"]["CurationTier"];
            service?: components["schemas"]["Service"];
            tracks?: number;
            duration?: string;
            upvotes?: number;
            upvoted?: boolean;
        };
    };
    responses: {
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description State conflict (e.g. class full). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor. */
        Cursor: string;
        Limit: number;
        FloorId: string;
        ExerciseId: string;
        SessionId: string;
        TribeId: string;
        ClassId: string;
        EventId: string;
        RaidId: string;
        PairingId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
        };
    };
    getRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recovery regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        regions?: components["schemas"]["RecoveryRegion"][];
                    };
                };
            };
        };
    };
    getCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
        };
    };
    getTenantBrand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandConfig"];
                };
            };
        };
    };
    listFloors: {
        parameters: {
            query?: {
                /** @description lat,lng */
                near?: string;
                /** @description meters */
                radius?: number;
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of floors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Floor"][];
                    };
                };
            };
        };
    };
    getFloor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floorId: components["parameters"]["FloorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A floor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Floor"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listExercises: {
        parameters: {
            query?: {
                muscle?: string;
                equipment?: string;
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of exercises. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Exercise"][];
                    };
                };
            };
        };
    };
    listFloorMatches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Floor matches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["FloorMatch"][];
                    };
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    programId?: string;
                    floorId: string;
                };
            };
        };
        responses: {
            /** @description The started session. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    logSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetInput"];
            };
        };
        responses: {
            /** @description The logged set + running session state. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Set"];
                };
            };
        };
    };
    finishSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tribeId: components["parameters"]["TribeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example XP */
                        unit?: string;
                        rows?: components["schemas"]["LeaderboardRow"][];
                    };
                };
            };
        };
    };
    bookClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classId: components["parameters"]["ClassId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    rsvpEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    joinRaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                raidId: components["parameters"]["RaidId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated raid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Raid"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    floorId: string;
                    code?: string;
                };
            };
        };
        responses: {
            /** @description Check-in result with XP. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        floor?: string;
                        xp?: number;
                    };
                };
            };
        };
    };
    listPairings: {
        parameters: {
            query?: {
                tier?: components["schemas"]["CurationTier"];
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of pairings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["Pairing"][];
                    };
                };
            };
        };
    };
    upvotePairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairingId: components["parameters"]["PairingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated vote state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        upvotes?: number;
                        upvoted?: boolean;
                    };
                };
            };
        };
    };
}
